### ISSUE TITLE
Make entire application usable only with keyboard

### ISSUE THREAD

**Issue by AAndharia** [AAndharia/OLCR#25]
Buttons : Shortcut keys with tooltip to show key
Labels show shortcut key for field next to it
Input fields : shortcut key (show with label)
Grid : Double Click should edit, up/down arrow for navigating in row
Escape : In all forms (except dashboard) close current one and go to previous one (discuss this with me)

**Comment by prupapara** [comment]
Done except Labels  and Input.
Please verify.

**Comment by AAndharia** [comment]
closing the issue for now.
