### ISSUE TITLE
Receipt Entry > Payment by cheque

### ISSUE THREAD

**Issue by kvora** [AAndharia/OLCR#34]
1. When payment is done by cheque ... bank selection and chq # should be mandatory

2. I did "MIS" type transaction - filled amount - then on entry form change payment type from cash to cheque ... it did "Total Received" field to Zero when I changed from "Cash" to "Cheque" ... and on Save & Print gives error for amount must be greater than 333 ... even though there is payment added in grid
http://screencast.com/t/gtkxPQF1RVG

**Comment by prupapara** [comment]
for first point #32 is already created and second point is fixed.Done Please verify.
