### ISSUE TITLE
Setting > Cashier

### ISSUE THREAD

**Issue by kvora** [AAndharia/OLCR#38]
There should not have functionality to delete currently logged in cashier... 
Here is the error log:

pF8Pjk3cFdT0TCbyTu2JkdGuSoHHCFCARVA/7WftrUUznL3Ku6bpT/5cUYtNDuo2uMnLtiU9W5fSXjbptFK7a7cJIGQIGiEji0FlDdQPGxrO6mK8eFC4zCtchiTHT/AnaJgy3r5RZ4UYLTAmFOHr52DNNNlGAebIYcPkislkDvue84k0No3kvCGXC02U0ISJbC0gQpXhvJAMQSLR0WuNf3CR9PWWovHE5NBW91e/qLDA/ea/ygIlVLvMojg/Gx3Ep7buAsc2KFp5TB6bggj1HYCJSGb4QRdFYNYkRfjeIv19jmCQvLVAsltHt7EE00JcPsa0cDCxmtnnRkNXub0VyHwoQyP1dB6LMFyQ2bOvmC+EBtzKZbuJV+4foZNNXofxjmipPkrdjizLFgqyspvaQKwvpk5rf6Qw7ySvKZUnpIDXqsu6+eSBtCHg5IB9BEAM4/3G+VszRY0lVZzhWIxLfRUsSd0AIhArrIPKKWuC7HOw4x4zdw5AFNtLhcpnYmTKabcOKiw7UInihRiyy/2KxHNETEH2q/tcy0Bg2H4fCTwxXEoF3ch4qRBvQUf37zAxsoIEK9syV/tSW1Vcl5B/ezXGWR67JKjAgY4HTW4QCh2us3NvrdoRcVdzjQfBa8HnSuaDYzPlEo8dpgeRvIX3Eg3vWf7vNV4lAuxzfQJCTZu5L2ETil7/eQCr+/SazvH4Di6J2L0iaGjOSCvKx42V5guOj/0gy+v11s0fK9vQAu8GLWxu/x2VwrVvrzNrC5VVhRWkLoaOGwt1fIHBq8VsXqfqI8PthhCQlfBuQpLaHB6xRmV4AZxz5nqWKxTT+c2aXow4w3ZJ23jjh3OInrz/tY++/2eI4zfQgsUPsjT2p8QbQpnE4TDZagbF/Ok/JmXOJ7rtAp0kw8QXJz5hbuj8I2p44j24qlqDC7hWkewuv1LNaCkQhoVdBmUEfgd5LCkhCmhe4Z0hs3nVmXE6GFBQ8K1nYpzRNIJX4H8l/MHnti6RrRd9tD2sVbPSF04e9gWPUmKQ2NXzPSythrDBZFBFCmXSywbm0Yos2FmGBTR4HuqwL+embgTa8OpkbSVhn4kcAcLEFjNH/amZSqHwAt8fhwnD4KNcWqsX+xp3RoVIAIIfYx/4dIMzEji8iZrT0Cs6R5Amolna+lRNVQ2pA65+ZRojWwYzTYQXKnY3QU3ziNzuPShCLvXc4G7awKPmet9nR6iovByQYp0NnPRIh7+ZS29mWQ2R4/v9oA5N9fEra4wabvAJzSF4n6lpbmSIkC/4B3k0PKLcFKFIsIPiHRKW+fB30soINXe6EiXCh4iQ7h2lEmLLwxab9I7L8+QPCjzeCLl3cLpUMveA7+GvmfeaBFqaE7mWwXmRY8qwqNXe9EXjQljCYiIdc3tRfQlqnH3rZZqimbodt6wnAT4ErjmHfX7l4olIcCjKhnO/mHBIOfWFAD5voxRaFGRY0FKE9IqRenv3M0zNG+oNMxe4+xGIG5d4O3fUqxWVrrYjZMQr7buX+yHVHuId7G2VuU1B48HL/lbtZznRwUfLRbuRxXpRAfRqmXt3RihFvieH8SggUGdw3hT5GUjQh3NPqM7nWVYkSNzOj92/dll82Iuv085Y4N16CWIpGse6BUqTrgXBDk/DVumSilx7LSjevXnL2QXz4e2v/OEJHDLu9e2mRKpaXE8vPjbWrYCHUS+XdZw+wP9d0Fxj9Jif1hHfI4co3yM5RnU25QQNBzq0nyTJWLi7AMrle4B3Oq+nKwAnQWXBassRUewPs8h80fzyzZ7ZVF8sxspViQ+zRvmbmo4m9sdS6nidpj6B+9P30p+c2qYJoiVIXsa66flDWtTVRdyJwVKvwpsQag0L+xYmKkqlIPfzuwn7ZxiRzKxVd5XcBHzTO+Cgr5JsbUOwAmWkLNOLSTONuJN/P24CbWg92y0gSSYfyubCYxJ6Ct2Qm//hbx/KdgKciloHfEjIoYdZUDGiR1JAmDQKeQleZzVb4h7nd5srRNtipbh5EjnSmK869R/kW130gI6EmPVNgA9Av/ZaSjmZ7Jc6Exv/5HN3qgF+LJSxK1Ow3qjKW9TEHz3x21VKxaoRgPO+5dpoAjx359/0dPhCWjeS0vJn1uMCWd8GcwE2NWB6XoSZZTSPXeGHO8OI65f/0MtugqWE6zsa2c6eLkZpE9jvTKs2MAj/VU52HZbguoF1Hut4Jp53YKSOp6L7hkThRDWqyelGRMkoGrXwrNc6qASzKoJieQGxvK/0xOTrvIWUSjkLKuoEv+wLOqvRQn5Yq9dVHRB5rkQz9GHPMa5guTMxBpF9WMqMiAXwgz9AXph/EzeTgyT5Ydz8Cm6K1XSTVR+MmsRFMWEqY5grCT7uGmaNCehRRKzYLrToL4gjgS+NgWBuqNJcpQq+QnrDEJ8z8FvPTkc5uOrwWh3nPQ5HSXB3kH55ZaeNdMmWGd/PyH+AwdAtw+k6p2Fu9PVKzmOW/k+geR+hMPm8StDY0326FkPaMKO2yrpVCQpsJIe6tfAi1u9hhh0xv0BSofSJ5sjnvDQKgg4jEZnGgblXCDCj+QdAVtK/xiFMAEVxz8st77nMIo/EM9M8BJum33fNAVx3b1C0f4TTBmnmbRQ22aHuiyOg/eYbIiM1oLYj6++EWWQwTU3XBRO4LUchW0Cq3oJ5P3j61Co2LUkN8Yri45zc92LILrKYCQS2GAO9LzT459egE4vARVzbHvekkTV1aIS7PeOD5VNTxHDw41MKxwH1/527lX0S1Sut+VSZzdhVn9fiXOeXvATLXlTFk0rhYU13ybm95XlrgDrjZz5dW+7bcyjU+vWDzxlyY84rXfx/6cJeHK+KR1BsdTHIbyXN9Fvf2XPGgVCV4Mjn+EPg3YL0RrH7aoZqprG0Scas8+KUSb35mXllLiiKdG2dwUZW4wnqE3Fx77hD5wGkzP42CO0PGln06JlG665Bcc5ryYpqurqD1ocSfBT2L8mMIp/UatvTcvlz7ABO2Up8Ps6M/9BuH5r6HV1ER4ZGSEx4ilPFiNH39NHEUnD3ms85fCdygBscmDU86PZ+7ncPTfjfstEZ/Hw+QN9GyFtDin02S5s1SAO9rvgCW/tO1Nq6Ku1K9YpupVYUH1htvMWw98a+7bCOqIBQYA8q49oHBJTOqrff2pH2dQQB+h5/jN+s+stYhqTOUASX5wzj2DCbKIREQlLoJNs9hd4SxPEmmZETcn1SuUX1PT6S2pRjGody5qw4fVHOS7ABSKuHPX23NBVltzf9uBHCobikEznxWVb0dIDfUKh9frXoNPbsSc2zXwtBT1KT+YEcQpcaeXaYtFOe15TU1WTkKkF1hjGSdtNARrpkG3XsICcQI8AiX9HODILJqzqH0ivTcISks2m8iRfmFjIufdiwjrxwwDU29sCCZ79FnMWNCQWImOi0gxMQsRz3JALoxb88lLrSbKV5yldiMChQGXhOT26Oui6vk08dxLNo+HNYAbcFwA5wYeSqZuzjOLJo/vh4kwqOlEEarf4GoyBNIcfpsCZnfKwvlD7zkqTlMaYvO0ujL3ajYvHxV8q45Y337rKnmwT7BKyxX80p8jfzqHDWIfpQ3ggdZnLp/aq5ElLpW+X1Shq24c4BGzIRYHhnwxtu/wuvGQadYc+BuUVi5dFLUNZTrSOrZ2b8/7J12PUbwbvMRqAo39CnyJzVO6d7s6Ri0aGz1En0ZHOSx9FJIsbeA8/jOdpW4nNtOPW6M7GmdajN+VVwEK609i87/CFWFwahnAqVPijI0ZC1nUYQqzAmTxxhgdivG2ROelLviLxbFigdK0117z0Hc/mvvo4hR3d73/OgDodiyiIvDDK/6n4b89LS5hKwrlSazkl2KgRFgArU3F1/PvpAV+nVUYQeVsbW8BvmfdcAi2vwaAzpDVTaSaPh4N0SvGmX48cP5lDsJNPkTJKwBWkPHLmA+5zeEPY46z/1FuBTOvQ9GteorJFP7AZgu4byi2wZm5iZ5Ribw2nsx72F3kgIUaHphH1OTe00yl2jOchJV7a6uAVegt+E5DYxPAI5vmSBMTd52DZ2TdySAFtWBB21RvJb3h/tqR6XXiGkjL7MjWCDuB0jZoHHqrQCH3fVnFiOVfEJqIXFn+ylFYjqdBpx3b9J/dY8YPkX+E6gHiKEPHgW+FCnrmOWIoLHezJ6mbLU7mm/NbnJ/Ekp6ku6QJajzfAnNvwaR6s9SQpDaJPQk5anUnHHUysZrO0eesGZmINpzGYhFRoijTrRE4HHndPvt2VJaHy+xRpPwzQ4GO5cSuOQ9qm7rYAu0prhNWJgIxunJwUmtY8yu6l/vpKLCcL1ECXIXBk7562JPTt6zfTvJCzf/Xlen/rRmqBOUgQ1rVRT5Rq5raBo6bFGV+5pn7d63iqd4jUtb8vOuOSSNyBjg31LjmwKoPEfTBMkpz+2R7pKmFMsQN8QUihGp4+r7FLB3feeQqy4JIM6awPTIkF/Zt+orBeCOvrNUPFoWU+8uUmFF6wOzX8nogwSb3/cZ7WfyTfTK00he2F+mJkpj/xjIkOCM1R0BMQ26y5bL1ILMJ6iKQ3S5vWW5rkuVgOpdoTU0I4tCMk93MdmqrLCszsh/ONCulrIP9qnXgRBJkUy90g9PaggRs/XyYobTs8Ls9Gw767Z2eAv1k22TRua8RjXsrHvb9GbCw9x772V9QpeVq+tCYtzRiuGowQEgFQZNj1oRUahFfyRmVcJNPOOAHAsnOVNT/b4EHfxZNsYEOqkpe4NXHOHyBiAgurTIoqArPqoi9jkYHouUanHgvBnJB/NaE9hLOZ8A4pIut52C6IJE+ozP7arp8FCpmg7v8ok4Nc231Q+gQ4zaO3XDHsxMr6Q0f6ntG9n3U78oayttcYt23LztNV0kLkv1990oLhQ6FiuTNgSAFQySBALLjlyk6oEF51ZdlZ47S3dcmb4mCx6Z7c8wkx99cDDtvJ8a8IvmhTVPJXTzadUwObYWtJAozpb/Ytdo91sqWifHPD2lEKtqpkCwrdgAQp8vdXx8oyWrGtDX46QHqDhXE406YqMUPeE0avmV8jNYLN2DGi4JVSWkb8f+9aOTWM70iqlKj4wBpGbwYlbR1qQfGS7JcYsUnmwiORGDidJIGlKEtWWq1Lu6inQecE+BA1rOjQy9upQ95qmT4J37s0P7qlG7/nzEgMHsPqd8FW9bmBl1TPZbghsMiz4C94UbMbyH5SQlsBHCCzfg4pWf71MW2tu5a5wuvmHD42bJbxEjAfkfeaHPME/WWp9hlvg+9ke/lsp97GihfcnTVYLdJqz1hpYQNyaSxKRShlajWGd4xUOoPCJio7rWy3gCMO9DnWvsPat3Gq0z8skmK2YrwzCdogepsEYa6cUEbvPIA7wXuyRbQLPCUO3sCD0vZ10OpW6HDVIk+XMcGqbdscLyTSlJC6gJYJrnjD98x+WHQ/i2NzJ9GTRL4mLNoUUf9b+9EFxQqsOfC45lFqQZCnQFnwVirWEXDoSH3bC831jMZdNw5SeChlY6xIdI4W44NSrK0P6ZLViJ1TclnVu1H9wGupeqDBzAqxC2HsfAvlcU67HUAo93CHiK8w/uP/i1J1vGDakzTB5ziA0F/xJf5IOXwf5I4C5IjJA9IuBR0v9bRR4kiSdD9ltbiioh1VzbMr8vxmScz1F8TaxMljInISijFe7usWwEnjMxc1h1woNkGPp1sxZ3tSnfmSzLaxCXaA3ZEQ6XLF85XuchuNPfQ2Lj6/cxuC2kbSCE9Jnv2kytAbqzUFLPPKIqpHoZ+TavBg6qqDO9NI75TTcpa4yvppr462FvMF6LQNrPQ+sl5JA5TjVJ353VilseGkiUp8XOLnOfWG4xPEdQQq0lURsKVZZNwdTEc0hctzPKNOTvncccDiVzt5o2/aMQWIIFoaDv0Bg0eRRz03b7XSyhBhFYuhI4JvDHXSvIEXYd/Nd3ks8VOZCVVW17+vMgAYUANEBS1JTPXteJBn3SFc66/zGVXfSpenPmS6f9HFcjKH6Af9bCW2UDDLl8OJyvj1/FK7zxDhr+oUDOB75HJRvz+57nYgQJBK7byEucM2nCqURBoWfHuO66wiabrghAt0T/jyGU9arAbn5fnhziSk/qbolu98fnnTaLxxUeSU3+zmYyrmSg8CsFo2q1BPCw3ElL32ilkVePl/bqszJwMlVR8LoQ42LL6+e3jScUdG6MvzEeEtRYezickyYuQSC891rLNKB9knk+xH9RxyhcoBmkEsetziCdz5khzmviRyK+dV6ktXnWPqeui1OEWx+IvJK4dIyb8KTrPbdSjdjimU/poBdMGukLMX5v1ToUb14U84Vmoz1QwQrl0s5buKKKOzGWYYilRGIjFSdpbwTy0uSyPEELnXcyJO+tLxs16AeoEb8Er8iOLqILPODqRBTu04Q1hshcFPUWIUJVOTrvqHY3FQ+DT3pjlO9DyxV9i5wb7u7F+YTJND9yUwFSkgACC5aCsDxbzLe6J9nSKsY/dF9UxrdV0M2VZDecmeudjMAyiBaRUWxLF8bykNRC2yFGztRZ+jI5GfjrkECwrlPQQ611VSbckJDKJovIaBWMJ0UZ3VbZIdAq8PdGkEgp03CWQNfZx6SPD9j6jKsTgqaoljG6TZZLd0eIa+zqkleQfnwO3sgWNaSueb8ZcYB3Gx33gix5WQxsfCS6RuDD3zdDGJ562xF4K05f0F3JyX5LJW1q16Lv0cpMzel+oT2ewDhcmYCFNlpHr2uizVrNUjoGr9rVexGz82CeYxTrX2ZC61mGwlG5ru8IKWj3jyQQVgpbpVJ/ow/G4TWr+C1BuLQXiG4KXCFgW2RmA6GxpheVbj34HsRoSH7Z1GmXXSP12iS2H6z4O4skb4UrmjZjU30z/L7IcPCDr/rjgOp823NZgRiICkXJyjWP7XvXvJ7BleR+6dHU34TLPzvxUorlYf5EpkLeM40Sh0x1pOp0FvrtPD7cW2JbU5FaPR5lP2Cx8BVNMZs/T4xoTjoieDJc/kQKT+hMuttHPC8xsCHAP8ckDqqLp2X3lCLcbRQnuDOoBJmPsOdtmASItLna2NcCU3xEWQ2H+w7uqaF6+j/P4qIQn/keeEJeAFDyzd/bqleMKwDnx4yLKkl1qCp5YYIUY4to80DJyTMnXKW2V5S/gnSDtagN+6oB+sU9dfnhqjxxndUL4rvhInWAKMRm42iQjI2jE6tWYZyZuvcPHsqDNFsFfRJvlMvr+fSZT2ynHltlVMkEf2HsUXSgdVfD+0nkqNt7Nx+SXHL1XOHF1aeHNCk2m2kZRSCaSpoEQUhT6QeBAPI2DzckULc1fCQJYltiRsOHVPC2o3IytQ0D66y/y0Ne8INGJzzMHfpcPKUip5arI7ZNkqL5p8DuH+ElLnNWMVGP8gg1qMTqi7OI5Ps26s1rKkFXhImVz/BcTHrdx5QD/EdXTWmmIbaX3RXCDC33WI5yXyb29GLbxlvule00EPgGurkDZAQ9V85BCJ5s9NOBhsiVbFqVAmB+qkWe21GakYLyT7/wIpmbGi0KKBrBQupj9sTe3AXJ8+cIbUIJ/MuoXt3zrgjhyCfyqD5hDdnYrBaZ0xTbxaBY3eWPXjvd+242jYGjw794ikQiYpYwTEaW4ZjvJS0lf7YywBbNjRZse4qp6w9/xjTg3Zq3LMFhvA56Ip5j20Jrnw9hcqiaOmYM8KcTfVba/fjQQJz/CuAcpMGdVGcHL0QU0iciqsfcz5bMV22YwzFBF3e/L1QX+2BEutfKGIRdaXk3/tQ4VNEHlj9jVcVHJX0JacmW27jpA9x3wu28CfQ16WDvd+MYS4D3rluaC+IYtZoazoZZ365yl9ICHlKVB9KnO8pSihvIP+K4DF/wW2x+0udGM0X77RzipOB62TMr9mQfmqc5iyiRn8ASG+ZFEURHZfiDmoJJ2ilqUdJrm901L6XsbZslG7CEfULdI+qKpZ9/2BLoMa9Yu/u99u8kphT86VSkGZAMefF5/OfhAMenuEpMVv9LSmvpmW7h7d6fbtBnumkvbFNKfZxEhM4xWP94BpTbC2c6qYUKt4qb39xuAakovtgLtK3KjPX6jZgDenEkgUnJ4Ywz8hDocOHfYJoKB4VUeDq0KiSsd+SMEx2AuTO0QSMTZUeYl/BIJikX80RmA8qEZANPQqlsKdiGdB9Zf4FNC6qU8WgsOJNbg0CfeAwgp8KjUoG8qw2J4hDfFehk92pfI+HX+SB1obHiPueH9gkPqNu3bbE9gNvvrNZfsFKrkLqn2tQy1hnQnyxMIje/uUYm0wbSG91K/REZdb0L4JCsruYcU1nuSXLkVGoHr7wHnpnyipGizdxK3ieNNuoCK7q6ZZUcClXrYiKYX3y9L1eknv3XvP57dmDDkF41QNCnVnfRRIaWM2s4z1ORYXqLYNe/uoWN+p7CGHpgSrV3deD/kk=

**Comment by prupapara** [comment]
Done Please verify.
