### ISSUE TITLE
Setting > Cashier > Validation

### ISSUE THREAD

**Issue by kvora** [AAndharia/OLCR#39]
1. On Cancel > validation icons should be removed from UI

2. There were no cashier name "admin" and then when I try to edit one cashier details and keep name "admin" - showing message "Can't set cashier name admin"

3. If I change the user name from admin to anything else... I can change password also

**Comment by prupapara** [comment]
Done Except 1

**Comment by kvora** [comment]
1. Now when you have disable text box when user name is "admin" > why to show this message when user click on "save" > http://screencast.com/t/Clr9bECkG6O

2. Showing wrong error message > http://screencast.com/t/dp4s8SK9K
    Steps to reproduce
    1. Click on edit for another cashier (Pankaj in this screen shot)
    2. Then immediately click reset
    3. then click edit for "admin" user and got as shown in screen shot

3. Following error came when I tried to delete "admin" - for other cashier delete works fine

pF8Pjk3cFdT0TCbyTu2JkdGuSoHHCFCARVA/7WftrUUznL3Ku6bpT/5cUYtNDuo2uMnLtiU9W5fSXjbptFK7a7cJIGQIGiEji0FlDdQPGxrO6mK8eFC4zCtchiTHT/AnaJgy3r5RZ4UYLTAmFOHr52DNNNlGAebIYcPkislkDvue84k0No3kvCGXC02U0ISJbC0gQpXhvJAMQSLR0WuNf3CR9PWWovHE5NBW91e/qLC3nYDB/+xJ7YCLa0VHApvQ+16Ky93FXg6TlG0BMl5q0kCm8vySevvDA8wA71GLrC5cMe10cw7rWAXDNgiYC3j2trVt6vT2RvtVwR84n1ETkvUOL+hnOMDDhvqjgZbJf9SmiCXoDtZEyn8t6iGzvSKOuEralj065JwOjREqZBIjlgN5dLBRZgb264c4Gi3kR4RwiBTe25/9uE4G1Of0t5zH8YKZs1Dgmby20hDrz0VOXG/IVTl7+fYI9DHsWAxmz2HOwmEE10kew3eBMDJrP3xZ4QGZxBGfpzsG7/f1zXWiT2xrbiKNsXyZUVSNJn/cMJ9EAwMqXyXh6dd9rsfnLSVtSFwr40Y08oPNiU3y3JZyIUtZJrOoOUiffu7UGDyZAtkQB4Jt+9xr1IEkNvUOgeMWi0QnwDqzYDOj0IzhB6FXnyF1/lVOCojiKZB4uJZN0GvaCITVKPJaqNDAi2D/bjGw22lffN0u8nUwEEKHAx1G1gcXxPX7OKcIfO6IhDMJ4HUzIHsCIayyymHOV+xo9i5FHTwxsxVENzD3u5QL+cFbBVuP9J+eT2dG6FvtGeBqafQrvE/Wd1q5w7rCU19lsd/WaZOUbuHW04c6cyJlnTYK7ERnkZjxrejPPm8cv4hOqcffZeMnp4j9YyRbv+iCP4/VG4AsvNoYKc0I+acI1ITm5AU1W4H2dxrIHsbb/1CVVuMIIpaEP6n2isz492qP8LTsw3PwXsGFlazonkv7n42oFSRNiBLn9bHHQz/K1W1tkHfXa8HfDaqF7/DpJXiyw5/xB/ZmrY/V7DY7YMJ6Nm+f+Z3a3JC0oi8m+4JzsJ5mhREXdZmmmj6O1h3RT49q4FPnpIHqJBmwgmw76ffQEmjO+XdLOKdydZKypSLfq1y4t5apmSsYbtur0JXeBSqyOcJvLj7YWcMnsVtKAAZPskgzdVBygk5PGAuftLiasglwcGIWc3ybzgKc9+6g3hnnSS8Z6rXi9RYMezAy7M/7PBFQAacvoJEqAny/D6GqSiZuQh/0QDVYr9aP6yuyw31HdNvKc8o24LfSz/lN7v/i/BiWKPtjGMcEZmVUMTQqEnKF1pTs/LrFy8+J6/7RrTNc78sbvsa3x3lf0ytgxA2GA/0SPe99UeCfek4klp3gy4P9Zq7KAH/iNabh/KfzzgKdntTdoOtnuA/60b9tbI+kwvRe1URgc4LEluVwfgO0UOca3MHi2EOaCLWzvJ0284v8/otv0rz+tS6X2GwDHpO4pnDwS2dpxx9RVlNWHdDeWgU6CAkOtwZ300BcnW2ZBS8CNQn1oive2M0cxMWvV5wT8BY9/85UL3lDWITyZ5o5ZGC/dAFTfzZim8L45GuBSxxJpo9+ctkgxJAgUX0KCgEskL1WqVkoJ4GcdofuN5mfOR9OUYAMrNrSRhNVgTnQeJW7jl2Zad/XmtAQ7XXBDUOlClHygsAhxrXBUN3yes3OvuhxlloQFSs2Os+sZQsVGzq4t4R8IB06jjZdF0qxBEkJvgFmVnrwCFz9m6Co0g+joT3wKYrBtVsL0ltkpw9jWKllgQQBOxUiiUVFoT9QswrN77X9cMeVtv4Di132tZuWqSle+oiej93mRA1xobPNO/b3jIrcc8pq9GufUmPORT+dpAJFFijMMY8A4z5WVRrIm8iU0jxL23JWA0fHlt86YQVt+X/9JiTiNoGIzwlY6oTtfeYiyLy5Aw3djcjDVMn/5ecrCud98mkV+uTmSCmPHHFCVE+inP0UnnBNzXIz/z9Da50P0hFPzh9BGx4u5MfqGYTALjXQuK1m6DkiGnVZlJ7T6WQDiXP2KHU75XzMcJhRFDU2015bzGo8+XwOFYG6IZOYijMwFgmgkXN48k7Hvas9+yPApOA3X36e+6hcRu4bmaH/eouRsVaVwvrmrbyZYPjvg9j2qrRKkZP8F46Qr06rfhumL4MO7nUtrxAjH22BA/KELi7uxCK50NomePnWAUHnHIXVnIwjCeDpN8hrBgu+Rfr2gpUnhtrstiga+52VHLiEMvPJdpfSozTkR65iO7qbe5FSMBrDfQ46k/kngFXZf7PRULfsuVJt3j29KpHpEBWlyhtJ1J6CB8ByEu34ynLttNccZXYzzxJXlB6rkiiRe/F62K4T547OGO9f7ZgdWf9mDiOAb6LT/67QruPEA4dXcMg0XYaxl177U0g0n+KISG6bbpQGu3C1H2qvDC2UF8VJH/g0IYBkmwbeZSabz41aTe/tg4kN+Eu7U6oODpTBUvxhd7gMDDcPRtwL9brNCZPilUIpXzTTc+vgb1ZGrODI9Kp1toiPjiKAr/BFYOwft6gG84pqPkgSV2oAxbGpgEaTAIAEhN9z2X8KuOSL7PB+nh+O3+1d+nQS9fZwoN5R5z9stVaYgSZb+mREL4mDdhk0bi7taQodYSlwnzsxNFqnRIdNcEe0gAxeGmgl3kX+kEecG1IqbUWU4OCi30DMLQrQ1sEK5k1YKy/0dVfgjMLsZbhgTSCoil2L0vozrdrB3nLPydX+IxLxjY1Scp0vjIHybA/zRaxFa+C/hVhtfHQSFjSnEfn2HtIrZSZmdcGWB15WbUItcg/szQFWBBLbbzBSWHkplu6juuCnpBz3ZpmlYA6Bw33sa0tCy4IZYL5QZxqZFElGd4J1yEDKKbGwa+EwMj5aUkVhnc2nozsWV2+G0HQQjVsDrHPdgWH25gG4PVENZEeCUtb1tgP7FE1OcXRiAT9AQfEfgi+dQkgGgEYIKTIS/j8HsdiEK1wRCUH2lIxiGeo4okiKP7OijIUer+S07Dzi3lniZqcKog4/do6++mWYdfHSD5c8VPyQSv8aq3g4PKIEjP+zv9A7PbmHs4If/um2gz1jYmzKctyGPH/eCXe7uIAobRQQTdvBJf6KosQcLLP+2qfgNWfg2eXH71WGjVGtOY7yY7o2MpKNp+BuRs4jQXJDP3SMoh2ZZ6O21RdjUxS1VD1/QKhM7m6BnX6HxLoMagc/rX+mHl0vXbgPyq9ETk/hlV3tPo9+NOfWxnbtmGWIgEQACmQGBmJOn2kWPedl2+qea/j/umymgfBK4677i5FtaHfGUXArqdddfT4OEa5CIEY7wur5ditS4uDbFSUUbrebxrzL9+hEkRPSjuMar1YQcw9m9D4GiaFxfHT2wwChLDwpnJdt3nkvcowzyuMNizD4z586HR9Ty/1O5vQrn0sjG1qanovp7/W8P8YTSDdHdxS9nR0TKQu8chnrChHoLlOQjoeJTmCn5HlRhSfNxUlSaojFatztUFB1J43eSCN8ogtKukL7vBlXd9W3XGDaJZaZLtjYEqWjVLT6OgNWsVDb8fiHdLubZjEHpfLdwAHcI4Af/zT/+jAUWb+ydng2iGP1IM10HbzM5SpOWOiI5HQAWyhpM3YQDiZLBN7dLE1mpzAwH1wG8D0sHzDRURTWjm+/hXl5qm6r3qMGK3f9MF3yIHNr8LpmesdNCZ+BDG6Gjm1UFGnDsLkRG0fHRaIaNhSVrBQlDEHwzsM0sNX3rH7WFolc7P6tPbphbjX7qvygs6Nh9WyngJY8tGR9fnkhHkSQdDFg4s9YG7v+11o2M7w7b3Z3yGc/Hh5L7aQ6h0tiJcNcWrwo9ZtAxIEYlE2sTUSxTCduZepemx0O/9aBYXR7Yph0FSwcp1Z+OFcIOk3pfRpMF0XFT6lK5PqKQbNBZxvzwG3SMOANYQf7NiQRfrGZwiR0jI4sZ3Dbq6xjHvY+K8skbgNXwmG7ploNsp7SQv2AcDVHo4qKLqWBL4foQ0mcIuCjDiTwyYRt46y9ZqczMCXLc1cvWoB7gWew8u3aop8xqjXaS7qGgrk8EwtvQhhFAfVon5aJ+vBW4yNibiemBw+0vy96kAnBmKlDE5JVTiMp8EH+mJ5G1Ag62FeWbHtKL83FwQaevrpIoY2KHHm4shemxaOuwCU9ZD6yJeqfW90S8m0geFF2DJVx2mcWU6eshSMFMuBxQYd+gYgCCpLDJWzmZ7lqAd3Sxhv+dfBP7ln1QBvR7LA8LYszJ8chuyt5QPwgu+e4qcOX6l17G1bCciGViCXr+fA2v3uFhrkkX/bsNHjFlbvZ/zrqpseQafVw1dnmQiUqumLtSxPKbs/HB9DAq/+JfGMaktjTK6iuDCTsbSwX0pYbrBRdoPgUUYrWoPQtjl4nZj4f8CNr48QqowdWm2vn8yjyzK2eouYUZHD7jtaob0EAlY4oScDAXQRTqu/RLlkI5TCqvWBx0qRCg4om8BP4JpAXGsY4iXZLvoqn266i5PDskEWx5M7xBoG798E02Cr4wZlgMyYYGRyhL9Wcg4cAqgCLM/kcLX1oxiPdcWa50Is0TF/5qRHdH76J30n6NGd2uedI/N1wtrbMMZSWZwg1hcIJOu84gxT41NzDRhO/81NQmY603dpV0WFghXR8syM9qaXNdZuvKcH9o7cb335rGRtY7P00dUHxEji+ViR9zogGGO2OfU+qHok5/8cCYEXvQDllsorFrvubTmnXyJVyvhAf4n/AVj9a4YiVlFPhJIVC5iwUf+Y1oAGMTVnynNVs5IvmMU95/tNY1JlTPOarFEXKG4KdPLVQ2SpzyvHrJ+5dw/qBbblVwdhl034q6QpS1+xhIVLUuPklwR+d09nNuQ45mxcJJd5UBqF07PAnt56sT+qMdKb0I7tBy5myNXcyqeNu92YjGEKuq0L6mG2DPtR6Nva7gOSCGzJcMK8/l00MzpKZS0+ZLGB3YrmFTy91dtebbbmQ0uTTWdp7+01IgcMiIANKguEXN1lPPJyZ/CVTz1FQzoS3rDAQS7KQar2vISm8SqvX5abwoiiqAPxnff5+HNq3X9duc6Scem6Hj7hfi84XCQ0FTdq/SQZA6EDzMo2a4G4C0dnvoWINFYIJHmjHNuc9IBLcUKnWBRXZOHTwEsS4PROwGykFn8rRWRUq9NfmM+/K+Olgk2BRjsikp1GyO2fJ/Z3xJOzWhI97Zsz8ImfDUF9ohJygBzm8ZL0PoSZ1Kaa156fo62xEElSpvB9ziC3pvMJwqeME4z3gqMZKHNFfNp4G9L1YjTPMVYYIIcv5fYVDRFgy9ExjemKKxbKn9D0LRe8v4aio6cX1r1i9dlvNs8LFYihgx99Qn32slzPYott0xN+YrJ5ygUdMW3KQkJcNg8A2KN8Vu3kCqnOvrbUnJJPxXZb9d9H4FMZLzAvrwl23tHxmKDgcGmOiR3lovZx4dYXq51TJVEgkWBlplNO68R2Ipw0eRmXk/LRUUIUSQj8uQqkHt2VEwxACsuPkFNhz/avY25I9p5+Z3oa22AjZLOEJmK5e+W2c8maHLDLaoobPwd+fMl5EAVtXVTWEI7SOfCJ9W2w249BTxWssDnpMrSK4aBtz47z2ZfDeLlsk7y96qOVLmX1fXfXwbT3nwDtQDm2izoeSZCFkMBaKFh8wsfN66SmTBzBBmjj4JtHUpYX05iFnT/FDEH0l6I4mE3EbWyphCJX5YL3bBUAUYYPK7E1zJVToXiXo0LfRLeHvaV0mOT37hGMR94mykCCZ7Rt7JJE4HN9NN90zP0ThEf/C70pPgaq5hjuUnItXnOFgVuUKp/oTR68v94mwINT6qp1mKJrMJmcAX2+mf2E5ABbKfzH/rz+iksYhYnqYXidn0lP4pa/VkX6OcPqiKPCMQURQEbXyJZ2b7maf7cDKEpQwia7FisIzSNEFneBl6EbJAMgWzPqdUqA4a+1tOS8KpQlyonMOtHQRAAsxWBlxrCGJZka7tHSvTGyw/6xMxALizps1Htc+3G40tsERJKOMIIc9/ySsy3UZXqX/0TP0yjDjQDD+u8Mx5QDYS9UqaCez1V8pqKyDdlIdz2Xz8xDFVjsD/bAGt1syTusmhGbI8nbUBDJ4kGhU59LVf2YR4MyvWQ3OmdSyYbEtZCVFGc72usnXqPrLLWzFymUMkuGNr5V3e0NfFkHZezCQq5F/NhFNQmbO5ek/4UYon5ZyFeIYdoxNFn0lFEFLY4yaQ6KI3KXeB9HPHzZqUFwpEyKby4n9w+NCzKIP8IXy7yT5UVicAc4JkerYNRip3RIGTz3JoEMUjInLonqSqMU6Lm05mwO+VMe13oXdya74iiDsaVFXHYg72ChbU978cjOsNimgZy5b9NwxIdsBfpXtRL7G2NMHE6v58pNi9J3QugCtRKA1wK0ms/UWqFDJpnaoDk3moThmwNeWJaG31hSa8wzH4OxJivNex5Jlq7mGX5dHrF4H/2lEho9T8UAuUPLkPcBxdxgaiHteafVvZDmY922+QYFpSzYFpqtWUFlLccDF0EpqPTq8Vc6ERGo3olMAhbdidye5HXycgY6C2bWnEurMPmnvD3jfloGOHv7yX+099zmYy6sh/9rxgr5zD/QO+MDG2HOMqPfwCJXmSsO7jo9AWs6bGVvP1gwVmuYDnGO3OVCr0lqHOtv9NtEJQyihpsdup9Kh6R2LtGZS4odUFOUTQ0Lu6SASL4O9dYc3gLQcXWZksUdQPEXbmZwAJuVv5QPYBjCvfxuNSysX74HBG5yUty+WYfwigPVEpbZyeaG/9x1MbWOQk9URFdhpOD/Q7WKoNuD1oN/TXcsajnDh0D8RuZLDUnHF++2UWDPAu4WdfpByxnlUllAZdlICQMzfw62cVULjjdEoya1ZMUO91mZfdYYsv/GrXGOseyNh+YdYGmu/ZX2xB5KPts5BijOYcQdVmt+snC8sLMLKUfnNOrrpwpTVwkZFn9fLZhnvrLuM8dQvpaN32vtgCr+nTxAE4v85YhqWSwDwvZukqqoRLx8SdK5EgTvDQBYJ+AIiKJjJreZ9sDKDEkJepWTiGhCZ74eJBe6ekzrr5lznk99nnk3jADvQsc6wKM/DKkCqdJvT9Atr/0VRIR1IJaaPJg8etyCMTiX8RzSNUCZ8u3QIIwmEx/uBzWo6gajiCy2egubfuG7ARL9W7x6vHR5I9iAXsA9hHxWmvN4vx3PNy59D23eKqBd1hYI516vIO6jMVVQlWgqySCpg4GDt7obD8hMBAi+UnqLPN/6nn3J6OZvxSXEUO+tkMlJptDNIEaG3r6+SWm84t/DCAH/HZsyfBcMQ1BxydGpQFNXvJlgV7F35PaPMRGz6fn8N4i4kKM5+y4vyzApoy0hhiLsFXBxmjGJ2yk+qUh3rxs/9CAdP8BjK9WRMSOX6qmHFiyMKKWMMk7Cayw91ZOfgn7Rl3LEhEPq4TEDHM8lEj1O3nx12NWH8SXWIALo155t0WJFfxRXecFEAGV4NENoxeGk5iXIdGnuUQ/BprHD10dPgBMTFFcCHnCYiUJ5uLIEljoyWohQ86NMfMhKpgyj/fsQ8yaYPK51c7iPZRwAtLESNGETzf3GbTym/tpRRiIHcdYGIFmIAFl9eLWFyvZLQbOTYYuQhM16kf8BH+LPjOonAmKE+VAAbJZNbrLzsQGQVizD+6xdGZSKQTIjDz8Py5Gkv9lsj6tbdUIyuXojRA31FwyQIwg6XGlIrq3dhGITNPUQRMDcMW/mspm3Yosy2dAuiyQwBu9VDwDe+UOLem71cQ5bDj93oaD8fw51syz1Pxhu5gq4EPnbOfL1C6Tgs3DLhS49s4s6i++oGkfpADiTB6Zx4XwBHFkVpl8l5WtIbwbmLPDDQiJn/yMO2x3UJecLwJ1prqzoL6T+h1p9ZJ6MGbQZbnlOk2Ilgez4XyL4QmIJUsZGP0GiAWQ3TxcaZ9V9ZeDnXo4b19N2VqymBvYr/V5wNBhiZmTGStPpXaU/wvRzIm0dOLVjNvTdAIqOt8+UA7OwHpRVQd1Y2UzzTL0bUOopSdMBwK4Gm4MxaBkNP2jgqqx92T/oonQEdBtONVjReZJPQFMJinS68XsTJRrl9y2ap4muF5bY0KGgCSsUqovNCY7AcyzcXROr0tRW6szNoK7zzXvRY1pBIIvxiGY25p9ssb/+p0eK17YuEyED6LHJteQfybycXZrWrKhtgOrsLYXCghAlyJPoAtiWSvFuLhBd9O1heb6Zejkn0w7EtsgnloS27qN+54lvGVI6R6DpoOyke4hgX8NjpTcuBV0WgtY8V+UJWRGqXA5u5DysrWnnhCuqbWbxKgX6dbM2/AnoluB86toBe+WpJLJdr9qbJdoWnbfbSHz00wLk3UAxYkt4RJMsqeE1+6iC2feXlsqTn5BWslsB38rKcj/2CWw1S8sCKLFENwy0UvhdkWjSIG5QpxcFNIBltKiqTtGHENIHhCdrSkDLteY+hs++grlDmpduohDalbwVh1/Kdpw7aVwncl6futixgjgvH+4HnUJcIZzV+coiGTiUU1+POFsfRGA0ZFQd0qsfNasAyz22BxftrkSX/J4bDXdALf19KmKHs1LvWWVFHe1JnJOPdMYHuPeKUXXrEveQM/NyY+sBgNfyqnkNAHoJO4f5fRUT+cyDDz6rYxfpklVndGHrcvP/9wVEEyoL6PsDhGwGiN3Ayo/B9g5CrzilNT0C0KqM7Y0m1l4UMetWkKaPwe1V+47bWmn4wlPJT6tBNDjt5b2esTBwfrJ5lpWKWFMMIkYvSEsLeZAkpZ7hA8wS0ME2MvAI/qcIUNT9sQ2Ubo4idvpDfTdHBsbUkErmYblBx9FYc2bw6BKq9Soy7wIXeys/zrRFKH/SBxyE+fM0rHAfu62xxNqCCJTsMSicx0tp3a4n7ocrr5JiEJGsM3HdmZREUP4FOHcLPbYlhny6YDC9GN0k89Axyig87M3Bpds27nVp2DeMx7WB+c6gts5mJBt0qwh3STQwZY49WeIlsm+z0Jx7JH/g2//2QEySJaW0V1FLJqRzG9NMwW5d1pDaCqTpYK5YRc1AId+APWXpN0tsopp4YzBG7PzIkAE6Ul7eMR4CYjdZ7Gu78uGiv7aWb9iHbOJFkDaHT83cyFg0j3BXFbUeROQ4H0KCoeFg92MeXy7M2rEmjym0oqz2mu+ucohfjmbz+QmANpvtBfDF8cUmZ4LXeX1KcVzoAjG4U4l5wSFAw88TsQXF9U6tPreZLUIuOKO3B+BH4BVDkHwMR4HJmHJwmqK7JjKpFJhOWeCfaAMbQYpYC2jksTxCywcZk7oFLBfz5KnEXd9ThL/9zlE5nTuXE

**Comment by prupapara** [comment]
Done Please verify.
