### ISSUE TITLE
Receipt entry > issue when bill type changed

### ISSUE THREAD

**Issue by kvora** [AAndharia/OLCR#44]
When I changed type from MIS to EBS after adding payment information > It does not reset page properly > http://screencast.com/t/Du7oxbIfCRh2

**Comment by prupapara** [comment]
Done.
Please verify.

**Comment by kvora** [comment]
Talked to Pankaj... as per him it is for user-friendly behavior and it is possible that user may have set bill type by mistake... so user does not have to enter it all again... Kept it for now .. if client wants it to reset will do that
