### ISSUE TITLE
Receipt Entry > Payment by cheque

### ISSUE THREAD

**Issue by kvora** [AAndharia/OLCR#47]
I selected a customer for receipt entry with bill type "EBS" 
Selected payment type "By cheque"

1. Entered cheque number does not get displayed in grid below

2. After adding payment details in grid... It was showing Total Received Zero and Amount and payment section to full amount - http://screencast.com/t/7VYcPN2DKluI

**Comment by prupapara** [comment]
Done.
Please verify.

**Comment by prupapara** [comment]
Done Please verify.

**Comment by kvora** [comment]
cheque number issue is yet not resolved.

**Comment by prupapara** [comment]
Done.
Please verify on next publish.
