### ISSUE TITLE
UI enhancements

### ISSUE THREAD

**Issue by kvora** [AAndharia/OLCR#48]
1. Bottom tables for payment amount and cashier details - Adjust spaces between controls and labels

2. Wherever amount field is show .00 always... even though there is round figure in amount

3. If possible make button's height same as textbox in receipt details and payment detail section - http://screencast.com/t/cgkdDvsZ

4. Active row color should be same for all tables/grid

**Comment by prupapara** [comment]
Done Please verify.

**Comment by kvora** [comment]
Yet not in all cases amount is zero - http://screencast.com/t/tWLR20jaSU

**Comment by prupapara** [comment]
Done.
Please verify.
