### ISSUE TITLE
Receipt entry > Amount field error

### ISSUE THREAD

**Issue by kvora** [AAndharia/OLCR#66]
Steps to reproduce:

1. Click on find and then press Esc
2. Now use tab to go to next field > that will take you to "Amount"
3. Now again press tab > here you get below error

pF8Pjk3cFdT0TCbyTu2JkdGuSoHHCFCARVA/7WftrUUznL3Ku6bpT/5cUYtNDuo2uMnLtiU9W5fSXjbptFK7a7cJIGQIGiEji0FlDdQPGxrO6mK8eFC4zCtchiTHT/AnaJgy3r5RZ4UYLTAmFOHr52DNNNlGAebIYcPkislkDvue84k0No3kvCGXC02U0ISJbC0gQpXhvJAMQSLR0WuNf3CR9PWWovHE5NBW91e/qLC3nYDB/+xJ7YCLa0VHApvQ+16Ky93FXg6TlG0BMl5q0kCm8vySevvDA8wA71GLrC5cMe10cw7rWAXDNgiYC3j2trVt6vT2RvtVwR84n1ETkvUOL+hnOMDDhvqjgZbJf9SmiCXoDtZEyn8t6iGzvSKOuEralj065JwOjREqZBIjlgN5dLBRZgb264c4Gi3kR4RwiBTe25/9uE4G1Of0t5zH8YKZs1Dgmby20hDrz0VOXG/IVTl7+fYI9DHsWAxmz2HOwmEE10kew3eBMDJrP3xZ4QGZxBGfpzsG7/f1zXWiT2xrbiKNsXyZUVSNJn/cMJ9EAwMqXyXh6dd9rsfnLSVtSFwr40Y08oPNiU3y3JZyIUtZJrOoOUiffu7UGDyZAtkQB4Jt+9xr1IEkNvUOgeMWi0QnwDqzYDOj0IzhB6FXnyF1/lVOCojiKZB4uJZN0GvaCITVKPJaqNDAi2D/bjGw22lffN0u8nUwEEKHAx1G1gcXxPX7OKcIfO6IhDMJ4HUzIHsCIayyymHOV+xo9i5FHTwxsxVENzD3u5QL+cFbBVuP9J+eT2dG6FvtGeBqafQrvE/Wd1q5w7rCU19lsd/WaZOUbuHW04c6cyJlnTYK7ERnkZjxrejPPm8cv4hOqcffZeMnp4j9YyRbv+iCP4/VG4AsvNoYKc0I+acI1ITm5AU1W4H2dxrIHsbb/1CVVuMIIpaEP6n2isz492qP8LTsw3PwXsGFlazonkv7n42oFSRNiBLn9bHHQz/K1W1tkHfXa8HfDaqF7/DpJXiyw5/xB/ZmrY/V7DY7YMJ6Nm+f+Z3a3JC0oi8m+4JzsJ5mhREXdZmmmj6O1h3RT49q4FPnpIHqJBmwgmw76ffQEmjO+XdLOKdydZKypSLfq1y4t5apmSsYbtur0JXeBSqyOcJvLj7YWcMnsVtKAAZPskgzdVBygk5PGAuftLiasglwcGIWc3ybzgKc9+6g3hnnSS8Z6rXi9RYMezAy7M/7PBFQAacvoJEqAny/D6GqSiZuQh/0QDVYr9aP6yuyw31HdNvKc8o24LfSz/lN7v/i/BiWKPtjGMcEZmVUMTQqEnKF1pTs/LrFy8+J6/7RrTNc78sbvsa3x3lf0ytgxA2GA/0SPe99UeCfek4klp3gy4P9Zq7KAH/iNabh/KfzzgKdntTdoOtnuA/60b9tbI+kwvRe1URgc4LEluVwfgO0UOca3MHi2EOaCLWzvJ0284v8/otv0rz+tS6X2GwDHpO4pnDwS2dpxx9RVlNWHdDeWgU6CAkOtwZ300BcnW2ZBS8CNQn1oive2M0cxMWvV5wT8BY9/85UL3lDWITyZ5o5ZGC/dAFTfzZim8L45GuBSxxJpo9+ctkgxJAgUX0KCgEskL1WqVkoJ4GcdofuN5mfOR9OUYAMrNrSRhNVgTnQeJW7jl2Zad/XmtAQ7XXBDUOlClHygsAhxrXBUN3yes3OvuhxlloQFSs2Os+sZQsVGzq4t4R8IB06jjZdF0qIJBrjdqT7+5bYjv27KgzgJoCeCiDjXHKyuxLsn1/T3bpA5VZBFM4R6gjjz/fm73m9UVb+h1aXrXf5wXRger3k9LBwB+7uBPDH5B88A9hWRHoCBv0F3zAFSeQ8En3mZ4gEVqzzDC6Jh+sz8BGAokI7ZMnvCSR1AK4/wdYY8VjXSNf2QbUdyBGyo1vybL8KA2MVdFXZ295/FW2a3+HS/iwH5fihnLyY/cW5539G+bkzceox3G9IGmBowsPoEQ9w8ERy55i6daZi+xdD8+H8U5ku6DfOsDXfg/c/7NTm4Uf2dHJs+Y3GL7aagsMsoC/fjh+whCLsBuY7WHIge0cj/LBLBUp3/KC6e5tmmNmHCOxY7i0P7+Hp/XYmVx+BlFM0tVnVjiIpxMAcyeEaMb4NDWnRLsbkrjbS7aeNZMh+O4Lz42YggVJ3FA6AL2Wvh+ZRSo5JDXdxAThdRT/EqzPvX5Q8xN4J8JTvhpWIhDb9GApmXBMHbLzLijSBhFQsQCMsCUpdrqdn7N2ulzampKw/jEZ4OXdQ54k8md2oSGipXzjvW8fzPaueSPDQQkX80wyLMR19UC0peHHbU0eInUswOP3826diuMtbWeQXkzZjh+W4NqLWbCCojrLPYIlQDGLk8IrPjLM1n/ux86UozYGDAbWrRw4ZeIpqkkBX9kJTH/AeVPzFsoJnJj3d8tZO5j6YRhLjMbZv6HAdUVPputFJgyUFHlCY1mOjBpq9ce/4hBPw0Mu6yQS9cSDMGeTKmnpPzScLGov6e8PpFFA4D4SfqmHunGVSKQqDqpBnL9SS8lsgu+1f6dTbo26U7NspeLFwVW4BO7Qtf6SKvg==

**Comment by prupapara** [comment]
Done.
Please verify.
