### ISSUE TITLE
Error while saving MIS Entry

### ISSUE THREAD

**Issue by kvora** [AAndharia/OLCR#68]
pF8Pjk3cFdT0TCbyTu2JkdGuSoHHCFCARVA/7WftrUUznL3Ku6bpT/5cUYtNDuo2uMnLtiU9W5fSXjbptFK7a7cJIGQIGiEji0FlDdQPGxrO6mK8eFC4zCtchiTHT/AnaJgy3r5RZ4UYLTAmFOHr52DNNNlGAebIYcPkislkDvue84k0No3kvCGXC02U0ISJbC0gQpXhvJAMQSLR0WuNf3CR9PWWovHE5NBW91e/qLC3nYDB/+xJ7YCLa0VHApvQ+16Ky93FXg6TlG0BMl5q0kCm8vySevvDA8wA71GLrC5cMe10cw7rWAXDNgiYC3j2trVt6vT2RvtVwR84n1ETkvUOL+hnOMDDhvqjgZbJf9SmiCXoDtZEyn8t6iGzvSKOuEralj065JwOjREqZBIjlgN5dLBRZgb264c4Gi3kR4RwiBTe25/9uE4G1Of0t5zH8YKZs1Dgmby20hDrz0VOXG/IVTl7+fYI9DHsWAxmz2HOwmEE10kew3eBMDJrP3xZ4QGZxBGfpzsG7/f1zXWiT2xrbiKNsXyZUVSNJn/cMJ9EAwMqXyXh6dd9rsfnLSVtSFwr40Y08oPNiU3y3JZyIUtZJrOoOUiffu7UGDyZAtkQB4Jt+9xr1IEkNvUOgeMWi0QnwDqzYDOj0IzhB6FXnyF1/lVOCojiKZB4uJZN0GvaCITVKPJaqNDAi2D/bjGw22lffN0u8nUwEEKHAx1G1gcXxPX7OKcIfO6IhDMJ4HUzIHsCIayyymHOV+xo9i5FHTwxsxVENzD3u5QL+cFbBVuP9J+eT2dG6FvtGeBqafQrvE/Wd1q5w7rCU19lsd/WaZOUbuHW04c6cyJlnTYK7ERnkZjxrejPPm8cv4hOqcffZeMnp4j9YyRbv+iCP4/VG4AsvNoYKc0I+acI1ITm5AU1W4H2dxrIHsbb/1CVVuMIIpaEP6n2isz492qP8LTsw3PwXsGFlazonkv7n42oFSRNiBLn9bHHQz/K1W1tkHfXa8HfDaqF7/DpJXiyw5/xB/ZmrY/V7DY7YMJ6Nm+f+Z3a3JC0oi8m+4JzsJ5mhREXdZmmmj6O1h3RT49q4FPnpIHqJBmwgmw76ffQEmjO+XdLOKdydZKypSLfq1y4t5apmSsYbtur0JXeBSqyOcJvLj7YWcMnsVtKAAZPskgzdVBygk5PGAuftLiasglwcGIWc3ybzgKc9+6g3hnnSS8Z6rXi9RYMezAy7M/7PBFQAacvoJEqAny/D6GqSiZuQh/0QDVYr9aP6yuyw31HdNvKc8o24LfSz/lN7v/i/BiWKPtjGMcEZmVUMTQqEnKF1pTs/LrFy8+J6/7RrTNc78sbvsa3x3lf0ytgxA2GA/0SPe99UeCfek4klp3gy4P9Zq7KAH/iNabh/KfzzgKdntTdoOtnuA/60b9tbI+kwvRe1URgc4LEluVwfgO0UOca3MHi2EOaCLWzvJ0284v8/otv0rz+tS6X2GwDHpO4pnDwS2dpxx9RVlNWHdDeWgU6CAkOtwZ300BcnW2ZBS8CNQn1oive2M0cxMWvV5wT8BY9/85UL3lDWITyZ5o5ZGC/dAFTfzZim8L45GuBSxxJpo9+ctkgxJAgUX0KCgEskL1WqVkoJ4GcdofuN5mfOR9OUYAMrNrSRhNVgTnQeJW7jl2Zad/XmtAQ7XXBDUOlClHygsAhxrXBUN3yes3OvuhxlloQFSs2Os+sZQsVGzq4t4R85Uld1mTpUjIjy42cJ6RS33KjT/lzE3e371UpOUdT+HoAvl+nQXYhp98GqFV4SN32ArEO5QrNv29HnpHaD+ECiYPJUXOE490uRd9abWcRIjLuxvezY7YCJrgOQN7zAwbD2VHrDEUA3vqvYC7v9cK5UY/E60cZfWE95SNQBNM7UvmMw+66Jre/PuOmygoQNguZLxh7161cCx9Actyx0iCQ3OFHGlF8sqct54pVXxBeQ+53RT2oCydr4lkZ3qJLEyxKSNpKNqRXKSNx6Pxe9rb5efQlmlGJVRJjq9zfwJKFfVsi6Q0XRNjIehiTvMmqyMwEYPFP9pXr/mjEDb15fcIT9IG8cEFBCPMw+WcHdJhtpNhxgHf+OmBelOFYzh0DaDsqxRskiS1zwUdA6B40/1YMxsUMGMxngf9hiGBUQc2QFmaexF126eFXMsMjd7GRPx8E/PO1vi0WJyRhZT4iTX5TIl3XDeijhNYqQMY+Yc7iGJ9OyYC1mAWCcLbQStPg5vcqrtqcvQmMAnosWdA6HnuRVEOKf/NlKXzjHgqDlHualW8LJuh6uugxC6lEEbSSTkvfe4ywJ8/MLXo7qSgddO8i4oNzMOE8J+F1bBmWTM7KqePlf1TaIMdSb+QHWHdPIdoUA5fLNGXqt+hY9JT2p/+kumY4IE1hp9Q2jG4nQeI+gEWsE5foetp0FxPkYAH89xY36OrnoSPKb5VPH0x/cyC/tHetuBxaJLtWljWtri5VXf3sxzWwtn4igyYiao8/9chcvJVrkdE0M8VlNkuVB1g2TXEMrscabtBpJBuN8nn8f8EOqLXVUKXLTSgTM259GKaPyYk7W7/Q8cD8MmaqInLi1tV3PEPZjpXRJQULej/3doypNDJuDA+l0eWgc3JMMXZtqIE8mfpyWDO5MSs5VImMiXDXD0DheSWLm/RgYfWAvy14Tk9sTXhqeeV//HacIytPqKnDWY0JvQ7UWHL9mhxxvdeaxEgVkfsmQkag5pkPIZaaCwYhDhROCdEgMPn9w7wuDN5sPYQvu3SwAUW3NhoOOQSDZnha0o+hRnY6EdP6kgwHgKuk+C8MdBFuVaOwNf9XWgTbdFoKoqzr7dk8Ux3uSFVio+LIznsiB2VtGPwUSRjXG+1k3BQSRlA3oXxMpor4hygJqRcKMSeJr7x698Vuuilks0/8RlWPzwOd+RzroSopvjcpN1fU9SSmGdi58c1QUn4staMSWlpj6RkaZhK9pN3omp9VAaUL5IEjH8S4OPIt5xQfgaXc1QnbNUg7gY0LQ9SceeW27xKqSoNZtVXPyrx10frBrQ/F0Vvx24TS+x7B4R4yZPqs3JegCEbvt0JB47+RycagnafRzpbDSWJdmdsjNVi6lunX+ZvR9aiSxDESJ/5zSuQyr1P0t1nLikQIGoO+t1k9t5UQBATepclxHMVkj//RZ20hGWZ/sXxt31ZcPExti4r2yFP/Wde8DyhqUXMUebz5Bjnpk1DDoSfDVyDIcj/astAR5bfMv/2y+M4BZYEmyKpf+67yPWmw2ZBmm9dObfVW7rpxH68Z1zgCUnJFrmi7bbqQ0Y1uhUcRY7FCkCFZ+d1O/nZ4VKD2OgG21AA9MmXeFYcBzcF4hvrP5lMqOn3fxqttWA+u8CInG0ROvWckt8tOlT+3H4KDl8p9BYcIJymh/lg2V94x7N7yWGSO1ReXs9sokKrlPI3/YsKbSCfUCEbDSP5O5+UhzQpR0LVrlBr/Qcrbj0eBU93LpWYwL3FbLLr5oY1ceXRXiq0fd2/vHmxEbVNVIHc5GvDNmU5LLb3j9bFihKJvhaJ5UnT6aVqGUfPGHjWlARjR+DYIRj17S6Mqs989JYvdOUSc0Zj0AzbvU9d7/Q/nkHxZSC3Kj6oH9T852X/x+o8cQwOhlNFqOOsjmwxU/KYgp0EJ+Ygv5Q+0wWBZnWLwRrj581epDdk0c7Xr2ItEQwomTtTBcJ6HJEy3B0ubGl2PUYIAxJ296uINgfiklh8VSn7nzzhkl23e+JGgbYxYsuANYtMEcBm1AeLUx0oZ0VOlz6PJkcA4xeE28ms1uIqfr0nAWgmAdg2bFIYmj7JZsPnkMIERLC6tEtgz3tjpE2r5S04Zl9zSaRvcmEMjZsAdDF6IZM4QghJT1dirPiPao3CYEUcQsBjoOchcwsCpqkj2w6vFwQAQ/NQd1bjv/W/a206PscqIRxD7/UGyE4iK5APe7mGTW9rSsaZ0ys6wqDO2KGwambQpc5d2wnPU86tS6wJGPo9j6jC0FAbYuFnT91YwTLrZBf9/h0ib2nLMmeWSpEERfukxzi4SeOK+MxnHeNfPAp+g5KmLaeQhZ0vbDa/oNJBoGYZ/qqYgJkB0Fw2d+n9uLlRHIPpj1KG6V2T1/sFC8uwdCnbxl1F+Oz1qyA8grUkZGjpfi1VtwfWsPuyfF9FrAP2TLwmFiy0kU8/aHLkzWrDzDdzG4wEGizhFpBmrglw4IBayCU9lg7eogsdAJyUhDiSPbsYiU5ijdjtOAz0tvwsUjoHHOcSVM1ciL6uZjW6B/WEgHdlBqEROsg8uHViUvMxFg+hDVPUqdhkyZvggXz7OBWVYEJZ/0QlX/ZVYv/pWt585rmSQWRbWU7NO0vr9aFIYfWT6skbJhRKOQSi2suj65sFWCuvtF0MkYrjWNZzQGd+n+ogfz+a6eflwHzYgpYOFZN8Q7POU/eK+fu/b74+IXYT4Gqap2StRhH8XRQ9K/s0TH/5KlLbVRROEsmv8R+t2sOEyrBfBV9PF1Rh+1UmiEiErkLDzqlnNb9W1ec3x/E9RPRUuwNSSukR9LYYKoNMl0bfsAAF60dA4YpzoSQepj95aWP1MRMdjBZWyVlJH0VaHa2xb/cELYWq9WUF287Tjux2zndfpH9O+CF8X6P95ZdC7/eblFaiMUOmAkv6pd64yWSecWzDOSSkGRknVqoSU6AvHNtL3WjfgxdX5uPWjBcOT+HKp3+17c1TPZ5p/Dl83RdNNYu0hMK3j+UBi7ocGDL2cTCl6ekBcHn/IWE3K3UOIC1so0yWw6CYw4IuyKujnxJVhFtHA2BV+WNhj8DbsSu45pBvX0DmKohj0mAW7og+s388AD6+qb2mgr0nK7/Ys/FGK+AvQ3UzBTfYVqHaXTV7vQ3lDyp8MVjm754X4YpQdqw9y7BxhMl5aY0HoSc1R+28b7u5bs9E7p33U0rB6Yjinm8UITRKrUma5oLSgAi+ZnsJ3FShizGY+pnc4s9RfoLgTzajDX025ayJNo8XnafGxRb8awP6hWxSorX1fIQbkd1RbwRWvZXnIV8KMstA3KzQZHYmXURd5Oymv/ZWeDBQXL+dLiBjlnVQL8CazFsPcLfDMVbwV0u8aAsM9YgJ/aP/gPq1mf5kyOByolElSLiM2NUxdr3+vLXJzfsIS8TFG2wznigK6kqubiK3ir3MXNzqD3kJA9U1sFy1WuQQgs/fXJtXf1SLFF0Jjxr1TJDS3cYIGVBcXcAogV0N8JxKrJfwIbqEFdOuu9zeTiXzCmOZUQYXBTjSRcJVn4VFI/f0UvLZLat39Cf1+MWwD68imBR4lKuEmZ9H2zFrLvvryvfxvSJkcpseSRwP6xAnYVdIJhwRIeDlZrqHWoVIrFUeLt2P5YXgQSv63ncv+UQOt+FHEwz8v3yyxSKgrDtiHTjbUHw0/MlRAtx1AfeWe2M26rCT32GftnQ8+LvDbZZUKLJdYrx7erqqsIBBcJDkRfo8GSbI02wO+wqgFGnN2UbMCd5h9a9ruQ7RdOkS4fSdTvKXCcqYMnpVXj1AagF0nQNpWIxuMyp0ZTs7cPxcJbQUDEow/v1juX3bQR147fVUVgeVpPX/NU583LA4PKvjrrTSDeaFCRmF6Sa1HaRL3UoRCCNeJBp8gobo+XmITX5INYTpr6zewd2vFMisT7AouccsvLoS/othWWTSmMI22ENTRxTYVd1zjf1+zWaGtVk2hPE5P83LF3PMb+kXrwst4r5CDHwPmOCEosUT+R9f5k/UMP0F26kO0IEwnGflqKMs/DFcImBXLtU2j0hG53VXiJorRVZfkVWGqaaa206rQ4Y1AMsNeVb76pkfOK1zkPtCoXVhHNBRwV4LDvew0y/51EKRaI8EKN7PK2kYiQIpcLL6x81gDxf+PxZrlHw+xVVdxYkQ/S0KFpCsCUtZwbKyeGj3WGxvbxhUFA9pqcTmaAS9KWMbiMXOJaQ3aiWvNlzteXL5HbJxSh/iaXp094Inj6Fs6L6gGKrrVky1XXHHIRh3odhfrtQy6W9OaYTvNGQSxKkC70zTl0T3QepwfknKtJdCnsO8B3rTOHjazWjTGTHSLO6zZeHU8toRZ5aQBqc6HiNhX71WdmvR+zxeJsk+8uqFgAdY9QsaZG8KrjmHS0an3ntFd6yKmgNRenN5ZdcxFE/A+2hM77HmR34U2jsvtWUeMMhNF8qB6ybtmuCbLF7ZKEtBEDty1WTgL0FIYN1RlflmoGbEXF4NrfkeZtBjzJZVwacKZgWuYJq/Hy9Dl3pvH1fAEKSQjTXoxeW1WMc/XY2V5OahaZ4Kcr81twi1/Q2zjaiV7fEvhN1d7+TG2YLrIdDM2IGoPch8ZCU+YliRwqj/6WyimsmulMZbm4l0egX1SPaExmtlxs7tfXj7Edk/K7e2yzACyN3FZNMkwk4Nycq13KfS97CMyxBTqJF5/NcGFt8XtjIgkUEr+Hu1/3IT3k71tepYYsZ9Wiw5OuEw8AfwlKAABppbtDrIQBC1uH6HUkr9zp9KJM7N8gozOxNa74DKeVA1hFL/lfvIg57CB8eovYy9GrvJ7o05e5UkJJHbvcgofayWXvx4tVkJJNZ3t2ywCCs3bhuIRbjBKhQvlOw0ASmw1FR6X/UJaiO6otAha3Ns/MRh3rJHUh9iCr4PNOo9SDzUT7A6UiBPDvT0Yc4I3wpvNktmBtEMX1z/6STTQ/9MNdOAcjT8KYbtZ53zosdP81aKon0AAVUO4zStmm8qgLYIfRZSCgy+9THwLcvQgGVI0bYFFqFwbjDLGEUioCLvppB/itjt8tevlALZpBTcXal2r3ASJEQnvbpAGSiXdGAYFfNr64GwojMtY9S1tqCn/T+3BOfPmgi9VihIm+jck8/VF1j7hViT3V+5T3e4xKTL7DGkBehPMN3bhVjsLQR3ZqT0v/DsrhEjSzpduQTmK761MKEf/qwApVlMfRJvarv7XVm9vbuGstGFzOXaQtp8tpJE8lNyrhlqcoDBXTieQG4zyBAGkm9sBJLZR8MK/HPmSvTAcC2U1glBre6sfXXtGpE+LnOLWokFk9GbABwLp4V7d/HHzI8Ocexmb56Xy/0yDEbQp620ftWDso2+v7WGO1GS1x3KrjfMLqmGXxfCWNl9zqiUKG1e+doPL1eObrk//u4yygdipSJKVp1XCIJ2dkPB4I82SlJF0JWhHBw4PYYyXg4XvBRKDXcy/6a3R0HDVt7CCir0DRpe44eJMgOJHXZIFgK0J2LL45BPaoL4yUjK+G2bT0SrgiLUwHNQ6OZotAt7v068HaAU02AA89wyBPC+sIHFhgQQncpcCx4nwWOVpEW4BNPQLZTPgvK2PbANsWY/YkvHvuEfCE1rz40sU5aGajpLLosY2T13JNTJohmvoRFVMzzoyd5GJGcoGFU6WqLpyvbUGTfzQ9hT66hRFd6OHwKYogImN0dyHPnSUq9OeF7VX59qM/87m7Gp/TWc2aDlfGrYvkyxHLPkv2rdaOwURwKgm0EuLwdjYHlc+MT+1F0IwwdtcrauAc67LkVMDjX9U+7kwLwE5rmhDO2WyTagBsPF6p8KWbFjIHhYI7GAj8ePj3z98dtJ9TO1M4qGlaCI+7iFLZa5E3OxIW6IoUmH8c2015K0l9EVko93yRgWBWsvJk4ejV7K3rTLrUPEFP2k2RQ9swtu4TB8HUuP8Qy27NxPW8ghCMDQ38RleLfjJSYYGu4C6L1d/Hxe7R6yPc7TS0yF1qkxaEXJMksTFDx4wjpFIhcSRYZVVrMObGHXoTW0PuKmEaDQfnaWXQlqH93qmQQkvs2sWcvlWWQBzCTr/lTYezWU0o423mdGy23XA/1XoHT1j/OCsF/pUCPSin6YkgtVJP6Pue+tePKPw5stsFfAUM2vgR9ubKyi6FT4H+mVlx6P4Kvx4ZU94j2MMNtZg1OqJBBdsc1MSJWaF3LFOXX3zQ51jEjqCoCQUAzYgRrjA/2S4NuzACZyCQxk77D2fcNsSlvAfUYBsOIngPcD2cWmlmXtJWrOaHbS9TekFhp9I2Z+4Y2eoLQtkj3aopHlt8TWn+B7E2YsEKYxm3nuXB0YKuNxGS8XWqaVMhm+3oR0MqOWjKjR0MeB80r0DC1IZwRW1RYjx5W8GpcS2XNGVcDyba40qswstbmA1vOYvCr/Jwh2WA9GsGEpASFvn9NdtxRJAGxk=

**Comment by prupapara** [comment]
Unable to Produce this error and unable to understand about error message

**Comment by prupapara** [comment]
this error is reproduce when user is not select transaction type.
don't worry now i have implemented validation in it filed.
