### ISSUE TITLE
Screen size of OLCR

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/OLCR#70]
Make the screen size of the OLCR to be the same size as the Project Property window as per initial requirement instead of expanding the screen so much that it occupies the whole desktop. This will make the other controls especial data Grids to reduce in size dramatically and gives the quality look and feel.The application is simple with limited and simple content requires small space.

**Comment by AAndharia** [comment]
@mnarewec  Please provide us exact maximum resolution you want and we'll be able to implement. Normally all desktop applications are full screen including visual studio project properties you have mentioned and the same way we implemented this.

Thanks,
Amit

**Comment by mnarewec** [comment]
@AAndharia , @prupapara refer this VS Project Properties page image. Whatever ever the size of the image, so should the size of OLCR 
![image](https://cloud.githubusercontent.com/assets/10192106/7292847/987cd1c0-e9e2-11e4-8aa2-682db13db0d9.png)
