### ISSUE TITLE
Misc Transaction Screen

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/OLCR#72]
Do not show Area code, show the Area Description

**Comment by prupapara** [comment]
The area code sample file you provided "AREACODES.reg" does not have description. If we want to display description in dropdown, it must be there. And we also have to make sure while importing the data.

**Comment by AAndharia** [comment]
@mnarewec - please provide feedback to this issue asap

**Comment by mnarewec** [comment]
OK. This issue is closed.
