### ISSUE TITLE
Bank Ref in Daily Bank Deposit and Internal Export Report

### ISSUE THREAD

**Issue by AAndharia** [AAndharia/OLCR#76]
@mnarewec  : In Daily Bank Deposit report and Internal Export Report there is "Bank Ref: 4302239" - from where it comes

**Comment by AAndharia** [comment]
@mnarewec  - please provide feedback to this asap.

**Comment by mnarewec** [comment]
43 - Centre Code (Area Code)
02239 - hard code it first. I will have to find out from client

**Comment by AAndharia** [comment]
@mnarewec  - ok we are still waiting for you to provide all the details and we'll implement it all together.

**Comment by mnarewec** [comment]
02239 is hard coded.

**Comment by AAndharia** [comment]
Closing the issue as its unapproved.
