### ISSUE TITLE
Receipt Entry > Cash transaction and bank code

### ISSUE THREAD

**Issue by kvora** [AAndharia/OLCR#78]
When user has selected payment type cash... tab from payment type to bank code selection should not open modal pop up... for cash transaction bank details not required

**Comment by prupapara** [comment]
BSB,dower,cheque-no  is required  or not and "bsb popup" functionality is discuss with @AAndharia  this task is enhancement.

**Comment by prupapara** [comment]
Already one enchantments task is open for this issue
