### ISSUE TITLE
MIS Entry > There is not transaction type data exist and tried to create MIS entry

### ISSUE THREAD

**Issue by kvora** [AAndharia/OLCR#80]
pF8Pjk3cFdT0TCbyTu2JkdGuSoHHCFCARVA/7WftrUUznL3Ku6bpT/5cUYtNDuo2uMnLtiU9W5fSXjbptFK7a7cJIGQIGiEji0FlDdQPGxrO6mK8eFC4zCtchiTHT/AnaJgy3r5RZ4UYLTAmFOHr52U/xG6Nn+6dz5cKZUuOADLnAmGvDKuCGoQXTMc3TzbI9lM7w7kk8SCM1FhZvh/W77eN2OrvbHH3opTDE9JUGBoMsSQQNURwtbAvaGa12nnIHweReDBLkU/O98BeKtyYbEakdrnH00CR/qSLB1NFz7iUYTIuEDdhLzBeXu/2i4hu6QmL1KzrxCT9rnFlshGDQXevJhT16o1h3mtVSbk41IH3DXJYHhvAltJAccjPWA7pn0tBKFiwdOmb+NK0VYoHUzRbhi+m8gnHCPAZPqTTbkuQaQiL1PqZKHyWKWc1wHxnwkrupb8yTOFVkdLR5nZWoie2n2AZGh+WseCb6A47hS8coNbxL4bLuW7IwOuEjY5UabIb19mFY2yhJev6ESBcnSO3zoxNQrN3voXP4ffhOMykFb03QDMNPeykRIQT/2ZMV0Rsf5W0xx/27Kj9tf+RqEAgtAh/PGA8X1DFVDqPyrSL6tKnWFrrY3CoIbREEqnTbcQrRGNZDJaIBDjA7PUv1TiEtGNJlsrAMP2dgDPcpOXBt842jWlbswlrae+eOwdEm0JXup+2fKGIlStzmtWaOsluSC/EW7Nz38ZCOj/m67NWrR7V17SurokbJ8sPXi5/CrdAKNyQ/37I/HJDZpIfWtAT+6LijS6VU2rq0CeQiwt+iOwhaEHj/bLIvFyglj4yS6z3EKYEHTKuNXFUhGE1dtWF1aCwkdlltIWOlaphLCmqfH2m3sUdtY89jESWxeVWCbOvDBTaDDcJ6PBpvfGBBx0uLvnw/NAWDEo3Ke1upC0P4xftAQDqh2koozYXxSNXv+71vHXCZSrpSv6B+lIJLPdBGkoesNmwZbR1UFpR7DLQGD3E8U0gem4K6nlbQUB5KWqxUPFMvSKAQhVTJS1/AWf/+/3DNU3SGU6eHcmgYGTguvFWoFRaokIlk9EHHXVnqNqQ0i4vyMDpnV3Z/GMLpl9TB/L7ODbkGOnWdud0RXrkTA//UDi9+75hwk6sqJ0xakJjjeTb/1iZs2bmxEdSpZa6OXEEhJ8CjJXSUlLPN0L6zE/pXX6KMsIsUqfKJ00MQtZlmVlUY2hxmWVykqc3Ck+NpdQKKX6/PbmTNnmsfvZl++bVCXCXXzHpZ42NSGaJMTqCKN8JCJbKxxeKJoJdWYkGf161kCRHb+eEy0TfjqGKjvBAX+kjWUjkF5CqB6LO4mAc54tw6vpmer4ClyLH+q1nyljGA6SwiHPkFlwsQ90Ho0UpQtN9yRviXyu6i6sYyMHhAkHNLPwpvRgX3CKyRxAvHduN7JEEfnyLv1sVpDL0cBSdAOGNlvob3G9kTZSDDipmUyMJSQe8kRo1ndGGlzjunsPeQBxpLUIwooza7uNnsSA5b/yR9ULF+/vKzmVrGw/DWyfQRP93/F6Efis8oQ82nVRMtuAdeL6gK4pOcl5nnnCpEqjP7UHW6ZvT9HF4QOsmvHVtKoLvdaUYbEcxRPZ8V33GjwRLHgY5tE/vDEbCGV9afkNk338lgOmeTdaa4JTJyG/y//wDrax0KpJ8J7Jb4NFqef3kfaZFkeaUjVGQfSvnmYb0Av5/xyYcRJebKVcM++I3nRM08cY/Q2m2uL2RjDF5mFKv8lj5x0EGRvuM6xdVeSuMWAvtedMn5tKhC9ODz2PLoOZD0Ywr0/RdmrMMsUtawoko3zV77z1MDnNLVxsHtHggnwnC5kmxWHjezkyl9e7qm7EQfax+cFvISlTytNia/BDoMa5aJVq3B+eze4sWM+cOmzC51PQfROYqmarMYv+pbb6JQwJ62m89yZdApsachbgTpnKQ4Td8cTkrnOFGhCJwvZbjAoBtgPA6GyxXKpNIn9thoYS8ult9jd7YQdfUxJpTJQbS7UZvFgaQDV2+J6sq5gWGeZfq7SWc160gPgogmUYP+Atvrgh9Wj7RXqnGqc+uDNVWVxKztNOEkgUzahuTFlswT+DQRh7b05AHVT0VvRUbdOUEpL7UtWOCJ+iRrKNyoMh4b8GBX+b2EdooF6nm/ANltrCxoprEeR8/OMoEnSsv4VxYSizv40XreytvqnxawppU8+I+L5jdy9eotXYsEn6EDg/DC3a2RKmDeZn5PDTyY1/yx2KWbqnmzm8no0Tt3oOxzIi5Gg2ys9rfTGL+JPq4LApcH7oevuG82XoM9CvWuL7ogt/Dih54/Gz6DXkCBCU7vDXoh87/1VaA+YzgQQAbS4chIawtytnDARLNy/FwqxyKtkeI/SISFNfPYqd1YCnQhFOOaKXTzUOhAhn3w2botV1SJhy9N+94KcgHc0qwmP7FXZPIhzbMc7MYApyGJ3BNAG+ovXdp5+yjUvHJF1/lvL4cJP4/IublMCslTo6E79ov7qDP9McyVjv3nIajI7G6pqObJfWRqPNIuwViZHP6imEqBhgU2XS5jP4L8qWslZergcPWFqDmDbvier+z7faCQUFGkc1Zw0dI4iT1Nn+oInp24OwHd0LMhWtoq4J83cj4x4DBfPBk38taMd32OSiIhFW+KBcjFsd05Vha9rhkM+Jj0m52vpGz6lHxG1rKD6LQa98agsaOw5K67wsToNitmtCrycWXY86kQBwIJ5EmLCE3OZKlPVEKl58kxAs4Dcqiwr1kdLlWjojzpMA/Vf29VjV/lGTE7dcEs0p7Lv4/+JzL5xirQu5r4S5PRXbLvqA5PmBOpbo0aB9uQKMextJikCUVhPzr6tVKbQGh4gK7+S68pP8YwO664Ud5GsJHbZfHP6N63wAPYogoc+SO5l0cp6U1A4pj+0Zg+pYfCQ==

**Comment by prupapara** [comment]
Done Please verify.
