### ISSUE TITLE
EBS & MIS combo

### ISSUE THREAD

**Issue by kvora** [AAndharia/OLCR#81]
In some circumstances, once MIS is selected and then after that we esc to close its window and then EBS keeps occurring ... after 5-6 try it shows bill type as EBS but shows MIS window

![ebs mis combo](https://cloud.githubusercontent.com/assets/7380353/5703260/72a76476-9a8a-11e4-8300-3ff4cd599e03.png)

**Comment by prupapara** [comment]
I have fix this issue Please verify.
