### ISSUE TITLE
EBS Entry > Change value not updated

### ISSUE THREAD

**Issue by kvora** [AAndharia/OLCR#82]
Steps to reproduce:

1. Select EBS Customer
2. Add Payment more than what actually in Customer Amount 
3. It will show proper calculation for Amount like if Customer has 100 , You entered payment for 200 > It will show Change 100
4. Now change bill type to MIS
5. Don't select anything in MIS.. Press "Cancel"
6. Now it will open Customer selection > there also press "Cancel"
7. And see the magic (highlighted in pic below)

![change issue1](https://cloud.githubusercontent.com/assets/7380353/5703415/5079f6be-9a8c-11e4-8c34-a2a82400bc3d.png)

**Comment by prupapara** [comment]
Done Please verify.
