### ISSUE TITLE
Change the label  'Customer' to 'Consumer'

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/OLCR#85]
Consumer is the term used for customer

**Comment by mnarewec** [comment]
Why a CR? the original application as it as Consumer. I don't why your developer change to customers?

**Comment by AAndharia** [comment]
Our apology, we'll change it to Consumer.

**Comment by prupapara** [comment]
Done Please verify on next release.

**Comment by mnarewec** [comment]
Done. Thank you.
