### ISSUE TITLE
Receipt Entry Screen Issues

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/OLCR#86]
1. One issue with the receipt screen is that when the EBS transaction type is selected and the
cashier wants to go to the ‘Customer No’ field; the ‘Find Customer’ dialog box automatically
appears: 
Recommendation: The ‘Find Customer’ window should not appear automatically when the cashiers goes to the ‘Customer No’ field for an EBS transaction. The cashier should have the choice of entering the Consumer Number if they know it. Only when the cashier is not sure of the consumer number then
they can utilise the ‘Find Customer’ window by pressing on the search button in the ‘Customer No’
field.

2. When ‘Payment Detail’ is of type any type apart from ‘Cheque’ and tab is pressed, the ‘Find
Bank Code’ window appears.
RECOMMENDATION: When the ‘Payment Detail’ is not of type ‘Cheque’, the next 3
fields(Bank Code, Cheque Number and Drawer) should be greyed out.

**Comment by AAndharia** [comment]
#2 will be a CR. #1 - we'll review existing system and let you know.

**Comment by AAndharia** [comment]
1 is a CR.

**Comment by AAndharia** [comment]
@prupapara  - please estimate this CR and let me know internally. Anything which is below 1-2 hours, should be treated as enhancement and should be implemented immediately.

**Comment by AAndharia** [comment]
Closing the issue as its unapproved.
