### ISSUE TITLE
Settings :Receipts Screen

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/OLCR#88]
Our receipt numbers are 8 digits long.
RECOMMENDATION:
A zero should be added after the centre code to make the receipt number 8 digits long in the receipt
number shown in the image below . The receipt number should be 43082091:
![image](https://cloud.githubusercontent.com/assets/10192106/6222393/93f44ad8-b69e-11e4-8b38-78cffdf46108.png)

**Comment by AAndharia** [comment]
Can't consider this as bug, as its not part of specifications.

**Comment by AAndharia** [comment]
@prupapara  - please estimate this CR and let me know internally. Anything which is below 1-2 hours, should be treated as enhancement and should be implemented immediately.

**Comment by AAndharia** [comment]
Closing the issue as its unapproved.
