### ISSUE TITLE
Settings : Cashier

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/OLCR#91]
There should be an option to check ‘Reset Password’ as it is with the old OLCR application. So when
the administrator’s set the application for cashiering, they put a default login password(olcr) and
check ‘Reset Password’.
When the cashier in the centres logs into the system for the first time, the system will prompt the
user to change the password to a password of their own choice.

![image](https://cloud.githubusercontent.com/assets/10192106/6222450/959f4008-b69f-11e4-95d2-2a58bfe365e6.png)

**Comment by AAndharia** [comment]
@prupapara  - please investigate if this is a CR or a Bug and inform me.

**Comment by AAndharia** [comment]
@mnarewec - we have verified this is not part of requirements, even we don't know what is the use of this date field. Please elaborate more on it and we'll send you the quote for this CR.

For your reference : 
find you email with subject "OCLR Revised Requirements" for final specifications we have used to provide you final quote.

**Comment by mnarewec** [comment]
Date field?? In the current system when admin user check the 'Reset Password' the the user who checks in next time will be required to change password.This is not a CR

**Comment by AAndharia** [comment]
This logic is not part of revised specifications, i've sent you email for the same. Please review.

**Comment by AAndharia** [comment]
@prupapara  - please estimate this CR and let me know internally. Anything which is below 1-2 hours, should be treated as enhancement and should be implemented immediately.

**Comment by AAndharia** [comment]
Closing the issue as its unapproved.
