### ISSUE TITLE
Receipt File Generated

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/OLCR#95]
The receipt file that was generated was not in the correct format that Gentrack will accept. We had
verbal discussions about the format of the file and you noted it down, however I didn’t give you
anything in black and white in regards to the receipt file format.
Please come and sit down with me and we will discuss the format of the receipt file.
The naming convention of the file generated was wrong:

![image](https://cloud.githubusercontent.com/assets/10192106/6222521/cbcdaed4-b6a0-11e4-957a-aca82b9b4f7a.png)

The correct naming convention of the file should be the centre code followed by the current date
and a number to signify whether it was the first , second or third receipt file for that day.(There can
be multiple exports done in a day due to banking schedules or a blackout may cause the cashier to
run an export when the power comes on again and restart a new receipt file etc..)
Therefore the naming convention of the receipt file would be as follows:

![image](https://cloud.githubusercontent.com/assets/10192106/6222527/e1db0e56-b6a0-11e4-9935-06ab92582d41.png)

The receipt file above would be for centre 43(Kundiawa) and it was for the day 21/01/2015 and it
was the first receipt file for the day. If there was a second receipt file generated for that day, the
filename would be: 43210120152

Also note that the receipt file doesn’t have a particular file type. It is not a .txt file.

**Comment by AAndharia** [comment]
@prupapara  - please investigate if this task includes any work that is CR or not and inform me.

**Comment by prupapara** [comment]
1. Please let me know from where can i get Center Code.
2. We have implemented this as per sample file provided to us and specifications, i don't remember we dicussed anything about changing the file format as well. I tried finding that in chat history but couldn't find anything. We'll have to treat this as a CR if there is a work of more than 1-2 hours. Please provide new file format (attach here) and we will let u know.

**Comment by AAndharia** [comment]
@mnarewec - please provide feedback on this, so we can decide and estimate if its a CR and send across all the details together.

**Comment by mnarewec** [comment]
(1) Sample of the Receipt File Format was sent to you together with the Requirements.

(2) Centre also refers to Area. The Centre code for the centre should be taken from the first two characters of the 'Cusumer Transaction File Name' 

![image](https://cloud.githubusercontent.com/assets/10192106/7340861/1d1acadc-ecda-11e4-8b25-ded5ae646059.png)

**Comment by prupapara** [comment]
* Would you please explain me the "54201120141" file fields for both types transaction 'EBS' and 'MIS'?
* Our old system is accept only one transaction type for a receipt, and our new system is accept multiple payment type for a receipt. in this case how to display this field in Receipt File?

**Comment by mnarewec** [comment]
(1) 54201120141 = 54-Area/Centre Code, 20112014- Date(DDMMYYYY), 1 - 1st Receipt File for the date

Your queries are not clear. I am online now. Please come online on Google Chat and will discuss.

**Comment by AAndharia** [comment]
@mnarewec 
1. We are asking about the field in the sample file you sent. Can you please read the question again in that context and respond and confirm if your answer still stands the same or not? If not, provide your final answer.
2. Sample file you sent is from old system. Old system was accepting only one transaction type for a receipt, and our new system is accepting multiple payment type for one single receipt. 
can you please suggest, how the format of the file will be affected (or say how data will be stored in file) now?

**Comment by AAndharia** [comment]
Closing the issue as its unapproved.
