### ISSUE TITLE
Export File Should not overrides

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/OLCR#96]
As there can be multiple receipt files for a particular day, there should also be the ability to create
multiple export files for any given day.
I tried to export twice but the system asked me whether I wanted to overwrite the existing file:

**Comment by AAndharia** [comment]
@prupapara - please verify if this is part of initial requirements or a CR. Just inform me internally.

**Comment by prupapara** [comment]
This is CR as per our discussion. Please see this screen shot. http://screencast.com/t/rYF4EFqH

**Comment by mnarewec** [comment]
When there is an existing file, it writes a '1' to the end of the file name, and if there is already a '1' it writes a '2'

This is what the current system does
;

**Comment by AAndharia** [comment]
@prupapara  - please estimate this CR and let me know internally. Anything which is below 1-2 hours, should be treated as enhancement and should be implemented immediately.

**Comment by AAndharia** [comment]
Closing the issue as its unapproved.
